### ISSUE TITLE
Source of the Dataset

### ISSUE THREAD

**Issue by emmiiorji** [stedy/Machine-Learning-with-R-datasets#11]
Hi,

Great job on downloading the dataset and reformatting them to match the format of the Machine Learning with R by Brett Lantz.

Could you please provide the link to the public domain you got the dataset from?

**Comment by stedy** [comment]
Hi most of these are listed by chapter in the README file and the URLs still work

**Comment by azharyy** [comment]
https://www.kaggle.com/datasets/buntyshah/auto-insurance-claims-data

**Comment by stedy** [comment]
Thanks but no idea where the dataset is from and sounds like the author Bunty Shah is not sure either
