### ISSUE TITLE
ML with R datasets - download 

### ISSUE THREAD

**Issue by Tianster** [stedy/Machine-Learning-with-R-datasets#6]
Hi Sir,

Thanks for collating all these datasets. 

I am new to ML and not sure how do I download these datasets onto my Mac so that i can practise the R codes. 

Can you show me please? 

Thanks in advance 

Tian

**Comment by mzakariaCERN** [comment]
Hello @Tianster,
I am not sure this is the right place to ask this question. Open issues are usually reserved for problems in the code or the data etc. 

Regarding your question, here is one way how to do it:

1. In your Mac, open a terminal and change to the directory where you want your data to be downloaded
2. Go to the git hub page you want to download it's data (Example the challenger data https://github.com/stedy/Machine-Learning-with-R-datasets/issues/6)
3. on the right side, you will find a button called "raw" click on it.
4. Copy the url you will get for the new page (in our example I got https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/challenger.csv)
5. put the following command in the terminal screen
wget name of url

so in our example it should be like this
`wget https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/challenger.csv`

this will copy the data to the directory you are at. I hope this helps

**Comment by stedy** [comment]
@mzakariaCERN Wow, nice catch! Yeah that would be great, thanks!

**Comment by Tianster** [comment]
thanks !
