### ISSUE TITLE
Error chapter3

### ISSUE THREAD

**Issue by saso008** [stedy/Machine-Learning-with-R-datasets#9]
hi , i have an error in chapter 3.
....
wbcd_n <- as.data.frame(lapply(wbcd[2:31], normalize))
View(wbcd_n)
summary(wbcd_n$area_mean)
wbcd_train <- wbcd[1:469, ]
wbcd_test <- wbcd[470:569, ]
wbcd_train_labels <- wbcd[1:469, 1]
wbcd_train_labels_n <- as.numeric(wbcd_train_labels)
wbcd_test_labels <- wbcd[470:569, 1]
wbcd_test_labels<-as.numeric(wbcd_test_labels)
wbcd_test_pred <- knn(train = wbcd_train, test = wbcd_test, cl = wbcd_train_labels_n, k= 21)

Error in knn(train = wbcd_train, test = wbcd_test, cl = wbcd_train_labels_n,  : 
  NA/NaN/Inf in foreign function call (arg 6)
In addition: Warning messages:
1: In knn(train = wbcd_train, test = wbcd_test, cl = wbcd_train_labels_n,  :
  NAs introduced by coercion
2: In knn(train = wbcd_train, test = wbcd_test, cl = wbcd_train_labels_n,  :
  NAs introduced by coercion

i convert variable to numeric but error not resolve.
do you have idea for resolving this error?
tnx.

**Comment by stedy** [comment]
Hi, this is not really the place for asking these types of questions. I would suggest searching on [StackOverflow](https://stackoverflow.com/) to see if anyone else has had this issue or opening a new question if not.
